public class TicketLinkToDto {
    @AuraEnabled public String linkId;
    @AuraEnabled public String linkType;
    @AuraEnabled public String ticketId;
    @AuraEnabled public String ticketName;
    @AuraEnabled public String summary;
    @AuraEnabled public String currentStatusId;
    @AuraEnabled public String currentStatusName;
    @AuraEnabled public String assigneeId;
    @AuraEnabled public String assigneeName;
    @AuraEnabled public String priority;
    @AuraEnabled public String ticketTypeId;
    @AuraEnabled public String ticketTypeName;
}
